name: Build Leaf 1.21.11

on:
  push:
    branches: [ "ver/1.21.11" ]
  workflow_dispatch:

jobs:
  build:
    # Run workflow only on main repo
    if: ${{ github.repository == 'Winds-Studio/Leaf' }}
    runs-on: blacksmith-8vcpu-ubuntu-2204
    env:
      MC_VERSION: "1.21.11"
      BUILD_NUMBER: ${{ github.run_number }}
      GRAALVM_ARGS: "-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Apply patches
        run: ./gradlew -Dorg.gradle.jvmargs="${{ env.GRAALVM_ARGS }}" applyAllPatches --stacktrace --no-daemon
      - name: Create MojmapPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="${{ env.GRAALVM_ARGS }}" createMojmapPaperclipJar --stacktrace --no-daemon

      - name: Prepare release notes and artifacts
        run: |
          chmod +x ./scripts/prepareRelease.sh
          ./scripts/prepareRelease.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          MC_VERSION: ${{ env.MC_VERSION }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

      - name: Upload Leaf
        uses: actions/upload-artifact@v6
        with:
          name: Leaf ${{ env.MC_VERSION }}
          path: ./leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar

      - name: Release Leaf
        uses: softprops/action-gh-release@v2
        with:
          name: "Leaf ${{ env.MC_VERSION }}"
          tag_name: "ver-${{ env.MC_VERSION }}"
          files: "./leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar"
          body_path: "./release_notes.md"
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_commitish: "${{ github.sha }}"
          draft: false
          prerelease: false

      - name: Calculate SHA-256
        id: hash
        run: |
          FILE_NAME="leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar"
          HASH=$(sha256sum "$FILE_NAME" | awk '{ print $1 }')
          echo "sha256=$HASH" >> $GITHUB_OUTPUT

      - name: Upload JAR to download API
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USER }}
          password: ${{ secrets.API_PASS }}
          source: "./leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar"
          target: "~/api/uploads/"

      - name: Insert build to download API
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USER }}
          password: ${{ secrets.API_PASS }}
          script: |
            BRANCH="${{ github.ref_name }}"
            REPO_DIR="/root/Leaf-${BRANCH//\//-}"  # Replace slashes with dashes to avoid directory issues

            [ -d "$REPO_DIR/.git" ] && cd "$REPO_DIR" && git fetch origin && git checkout "$BRANCH" && git reset --hard "origin/$BRANCH" || git clone --branch "$BRANCH" --depth 1 https://github.com/Winds-Studio/Leaf "$REPO_DIR"

            # Proceed to insert the build into the API
            cd ~/api/cli
            node insertBuild.js \
              --projectName leaf \
              --projectFriendlyName "Leaf" \
              --version ${{ env.MC_VERSION }} \
              --versionGroupName ${{ env.MC_VERSION }} \
              --versionName ${{ env.MC_VERSION }} \
              --build-number ${{ env.BUILD_NUMBER }} \
              --repositoryPath "$REPO_DIR" \
              --storagePath /root/api/storage \
              --download "primary:/root/api/uploads/leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar:${{ steps.hash.outputs.sha256 }}" \
              --buildChannel experimental
