name: Publish API

on:
  push:
    branches: [ "ver/1.21.8" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      GRADLE_MEMORY: "-Xmx4g -XX:MaxMetaspaceSize=2g"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Apply patches
        run: |
          PARALLELISM=$(($(nproc) * 2))
          ./gradlew -Dorg.gradle.jvmargs="${{ env.GRADLE_MEMORY }}" \
                   -Dleaf.patcher.parallelism=$PARALLELISM \
                   -Dleaf.patcher.incremental=true \
                   applyAllPatches \
                   --stacktrace --parallel \
                   --max-workers=$PARALLELISM \
                   --build-cache \
                   --no-daemon

      - name: Build
        run: ./gradlew build -x test

      - name: Publish Maven API
        continue-on-error: true
        run: |
          ./gradlew :leaf-api:publish
          ./gradlew publishDevBundlePublicationToLeafRepository -PpublishDevBundle=true
        env:
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
