name: Publish API

on:
  push:
    branches: [ "ver/1.21.11" ]

jobs:
  build:
    # Run workflow only on main repo
    if: ${{ github.repository == 'Winds-Studio/Leaf' }}
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      GRAALVM_ARGS: "-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Apply patches
        run: ./gradlew -Dorg.gradle.jvmargs="${{ env.GRAALVM_ARGS }}" applyAllPatches --stacktrace --no-daemon

      - name: Build
        run: ./gradlew build -x test

      - name: Publish Maven API
        continue-on-error: true
        run: |
          ./gradlew :leaf-api:publish
          ./gradlew publishDevBundlePublicationToLeafRepository -PpublishDevBundle=true
        env:
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
